baseURL = 'https://o1on.com'
languageCode = 'en-us'
title = 'o1on'
theme = 'ananke'
canonifyurls = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    pre = "info"
    url = "/about/"
    weight = 1

[taxonomies]
  tag = "tags"

[params]
  authorName = "Priyanshu Tiwari"

[permalinks]
  post = "/:slug/"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"